import type * as Types from '../../../graphql/generated/schemaTypes';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type MovePurchasedItemsToPantryMutationVariables = Types.Exact<{
  shoppingListId: Types.Scalars['ID']['input'];
}>;


export type MovePurchasedItemsToPantryMutation = { __typename: 'Mutation', movePurchasedItemsToPantry: { __typename: 'MovePurchasedItemsResult', movedCount: number, skippedCount: number, targetPantryId: string, targetPantryName: string, movedItems: Array<{ __typename: 'MovedItemInfo', shoppingListItemId: string, pantryItemId: string, itemName: string, quantity: number }>, skippedItems: Array<{ __typename: 'SkippedItemInfo', shoppingListItemId: string, itemName: string, reason: string }> } };


export const MovePurchasedItemsToPantryDocument = /*#__PURE__*/ {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"MovePurchasedItemsToPantry"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"shoppingListId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"movePurchasedItemsToPantry"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"shoppingListId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"shoppingListId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"movedCount"}},{"kind":"Field","name":{"kind":"Name","value":"movedItems"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"shoppingListItemId"}},{"kind":"Field","name":{"kind":"Name","value":"pantryItemId"}},{"kind":"Field","name":{"kind":"Name","value":"itemName"}},{"kind":"Field","name":{"kind":"Name","value":"quantity"}}]}},{"kind":"Field","name":{"kind":"Name","value":"skippedCount"}},{"kind":"Field","name":{"kind":"Name","value":"skippedItems"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"shoppingListItemId"}},{"kind":"Field","name":{"kind":"Name","value":"itemName"}},{"kind":"Field","name":{"kind":"Name","value":"reason"}}]}},{"kind":"Field","name":{"kind":"Name","value":"targetPantryId"}},{"kind":"Field","name":{"kind":"Name","value":"targetPantryName"}}]}}]}}]} as unknown as DocumentNode<MovePurchasedItemsToPantryMutation, MovePurchasedItemsToPantryMutationVariables>;