import type * as Types from '../../generated/schemaTypes';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ConvertQuantityQueryVariables = Types.Exact<{
  pantryItemId?: Types.InputMaybe<Types.Scalars['ID']['input']>;
  quantity: Types.Scalars['Float']['input'];
  fromUnitId: Types.Scalars['ID']['input'];
  toUnitId: Types.Scalars['ID']['input'];
}>;


export type ConvertQuantityQuery = { __typename: 'Query', convertQuantity: { __typename: 'ConversionResult', value: number, displayText: string, unit: { __typename: 'Unit', id: string, name: string, symbol: string, type: Types.UnitType, displayAsFraction: boolean, minPrecision: number, autoConvertThreshold: number | null } } | null };


export const ConvertQuantityDocument = /*#__PURE__*/ {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"ConvertQuantity"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"pantryItemId"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"quantity"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Float"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fromUnitId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"toUnitId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"convertQuantity"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"pantryItemId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"pantryItemId"}}},{"kind":"Argument","name":{"kind":"Name","value":"quantity"},"value":{"kind":"Variable","name":{"kind":"Name","value":"quantity"}}},{"kind":"Argument","name":{"kind":"Name","value":"fromUnitId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fromUnitId"}}},{"kind":"Argument","name":{"kind":"Name","value":"toUnitId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"toUnitId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"value"}},{"kind":"Field","name":{"kind":"Name","value":"displayText"}},{"kind":"Field","name":{"kind":"Name","value":"unit"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"symbol"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"displayAsFraction"}},{"kind":"Field","name":{"kind":"Name","value":"minPrecision"}},{"kind":"Field","name":{"kind":"Name","value":"autoConvertThreshold"}}]}}]}}]}}]} as unknown as DocumentNode<ConvertQuantityQuery, ConvertQuantityQueryVariables>;