fragment ItemCore on Item {
  id
  name
  version
  updatedAt
}

fragment ItemDisplay on Item {
  id
  name
  imageUrl
  images { url kind }
  netWeight
  displayUnit {
    id
    symbol
  }
  categories {
    id
    isPrimary
    category {
      id
      name
      color
      icon
    }
  }
}

fragment ItemFragment on Item {
  ...ItemDisplay
  description
  dataSource
  type
  storageState
  showInOnboarding
  shelfLifeDays
  shelfLifeOpenedDays
  popularity
  status
  visibility
  tags
  nutritions
  ingredients
  createdAt
  density
  defaultConsumeUnit {
    id
    name
    symbol
  }
  defaultConsumeUnitId
  defaultConsumeIncrement
  displayUnit {
    id
    name
    symbol
  }
  units {
    id
    itemId
    unitId
    isDefault
    isPreferred
    isCommon
    packageSize
    packageDescription
    retailUnit
    usageContext
    recommendedFor
    minQuantity
    maxQuantity
    quantityStep
    averagePricePerUnit
    createdAt
    updatedAt
    version
    displayNameSingular
    displayNamePlural
    contentUnitId
    contentUnit {
      id
      name
      symbol
    }
  }
  brands {
    id
    brand {
      id
      name
    }
  }
}
