import type * as Types from '../../generated/schemaTypes';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetUnitBySymbolQueryVariables = Types.Exact<{
  symbol: Types.Scalars['String']['input'];
}>;


export type GetUnitBySymbolQuery = { __typename: 'Query', unitBySymbol: { __typename: 'Unit', id: string, name: string, symbol: string, type: Types.UnitType, isMetric: boolean, baseUnitId: string | null, conversionFactor: number, notes: string | null, isCommon: boolean, sortOrder: number, createdAt: string, updatedAt: string, baseUnit: { __typename: 'UnitRef', id: string, name: string, symbol: string, type: Types.UnitType } | null } | null };

export type SearchUnitsQueryVariables = Types.Exact<{
  query: Types.Scalars['String']['input'];
  type?: Types.InputMaybe<Types.UnitType>;
  limit?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;


export type SearchUnitsQuery = { __typename: 'Query', searchUnits: Array<{ __typename: 'Unit', id: string, name: string, symbol: string, type: Types.UnitType, isMetric: boolean, isCommon: boolean, sortOrder: number, displayAsFraction: boolean, minPrecision: number, conversionFactor: number, baseUnitId: string | null }> };

export type GetCommonUnitsQueryVariables = Types.Exact<{
  type?: Types.InputMaybe<Types.UnitType>;
  limit?: Types.InputMaybe<Types.Scalars['Int']['input']>;
}>;


export type GetCommonUnitsQuery = { __typename: 'Query', units: Array<{ __typename: 'Unit', id: string, name: string, symbol: string, type: Types.UnitType, isMetric: boolean, isCommon: boolean, sortOrder: number, displayAsFraction: boolean, minPrecision: number, conversionFactor: number, baseUnitId: string | null }> };


export const GetUnitBySymbolDocument = /*#__PURE__*/ {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetUnitBySymbol"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"symbol"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"unitBySymbol"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"symbol"},"value":{"kind":"Variable","name":{"kind":"Name","value":"symbol"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"symbol"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"isMetric"}},{"kind":"Field","name":{"kind":"Name","value":"baseUnitId"}},{"kind":"Field","name":{"kind":"Name","value":"conversionFactor"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}},{"kind":"Field","name":{"kind":"Name","value":"isCommon"}},{"kind":"Field","name":{"kind":"Name","value":"sortOrder"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"baseUnit"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"symbol"}},{"kind":"Field","name":{"kind":"Name","value":"type"}}]}}]}}]}}]} as unknown as DocumentNode<GetUnitBySymbolQuery, GetUnitBySymbolQueryVariables>;
export const SearchUnitsDocument = /*#__PURE__*/ {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"SearchUnits"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"query"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"type"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"UnitType"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"limit"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"searchUnits"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"query"},"value":{"kind":"Variable","name":{"kind":"Name","value":"query"}}},{"kind":"Argument","name":{"kind":"Name","value":"type"},"value":{"kind":"Variable","name":{"kind":"Name","value":"type"}}},{"kind":"Argument","name":{"kind":"Name","value":"limit"},"value":{"kind":"Variable","name":{"kind":"Name","value":"limit"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"symbol"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"isMetric"}},{"kind":"Field","name":{"kind":"Name","value":"isCommon"}},{"kind":"Field","name":{"kind":"Name","value":"sortOrder"}},{"kind":"Field","name":{"kind":"Name","value":"displayAsFraction"}},{"kind":"Field","name":{"kind":"Name","value":"minPrecision"}},{"kind":"Field","name":{"kind":"Name","value":"conversionFactor"}},{"kind":"Field","name":{"kind":"Name","value":"baseUnitId"}}]}}]}}]} as unknown as DocumentNode<SearchUnitsQuery, SearchUnitsQueryVariables>;
export const GetCommonUnitsDocument = /*#__PURE__*/ {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetCommonUnits"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"type"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"UnitType"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"limit"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Int"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"units"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"isCommon"},"value":{"kind":"BooleanValue","value":true}},{"kind":"Argument","name":{"kind":"Name","value":"type"},"value":{"kind":"Variable","name":{"kind":"Name","value":"type"}}},{"kind":"Argument","name":{"kind":"Name","value":"limit"},"value":{"kind":"Variable","name":{"kind":"Name","value":"limit"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"symbol"}},{"kind":"Field","name":{"kind":"Name","value":"type"}},{"kind":"Field","name":{"kind":"Name","value":"isMetric"}},{"kind":"Field","name":{"kind":"Name","value":"isCommon"}},{"kind":"Field","name":{"kind":"Name","value":"sortOrder"}},{"kind":"Field","name":{"kind":"Name","value":"displayAsFraction"}},{"kind":"Field","name":{"kind":"Name","value":"minPrecision"}},{"kind":"Field","name":{"kind":"Name","value":"conversionFactor"}},{"kind":"Field","name":{"kind":"Name","value":"baseUnitId"}}]}}]}}]} as unknown as DocumentNode<GetCommonUnitsQuery, GetCommonUnitsQueryVariables>;